### ISSUE TITLE
Adding new servers and removing obsolete servers

### ISSUE THREAD

**Issue by ChocoTaco1** [amineo/discord-battlebot#32]
20th server is DOWN currently and needs removal.

Adding potential new servers:
Very Scary's AIM TRAINING - 29/64 (245)
https://cdn.discordapp.com/attachments/317024224688734218/993141256735707156/Screenshot_from_2022-07-03_09-00-31.png
Server has bots
AIM [ 0/64 ] *Not counting bots
A way to handle bot counts in the monitor
148.170.171.67:28000

Zy | Arena Duel TG Siege
https://cdn.discordapp.com/attachments/317024224688734218/993141279842127882/Screenshot_from_2022-07-03_09-00-43.png
No bots, EU/London? server
ZY [ 0/40 ] or ARENA [ 0/40 ]
67.188.157.237:28000

**Comment by amineo** [comment]
20th replaced and new servers added: b99ed18250e2191190c199c905814f3d60ea7db
