### ISSUE TITLE
The ability to post a query indefinitely

### ISSUE THREAD

**Issue by TacoDeChoco** [amineo/discord-battlebot#5]
Have the ability to leave a query posted thru the use of a command like 'post'

`!battlebot taco post`

So the 5 minute autodelete is ignored and the query stays up indefinitely.

Uses include if you're trying to get people to join and you want them to see the population of the server and whois online without having to worry about autodelete.

**Comment by amineo** [comment]
Added in v0.7.4 
`!battlebot taco post` will post query results indefinitely.
 `!battlebot taco 1` will post query results for 1 minute before auto-deleting.
